version: '3.9'
services:
  web:
    container_name: gleampkg
    build: .
    ports:
      - "3000:3000"
    environment:
      REDIS_URL: redis://R3d!sP@ss:auth@localhost:6379/1
    links:
      - redis
    depends_on:
      - redis

  redis:
    container_name: gleampkg_redis
    image: redislabs/redismod
    command: redis-server --requirepass "R3d!sP@ss"